apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowbooks-web
  namespace: yellowbooks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yellowbooks-web
  template:
    metadata:
      labels:
        app: yellowbooks-web
    spec:
      containers:
        - name: web
          image: <ECR_WEB_IMAGE>
          ports:
            - containerPort: 3000
